// PARTE 4: Datos históricos 1998-2026
const dataP4 = {
    1998: {
        hito: "La Final del Siglo: Ascenso ante Belgrano en una definición por penales inolvidable. El regreso a Primera de la mano del Tigre Gareca.",
        torneo: "Nacional B 97/98",
        plantel: [
            { num: "1", name: "Mario Cuenca", pos: "Arquero", info: "El gran capitán y emblema; pieza clave en la tanda de penales." },
            { num: "4", name: "David Díaz", pos: "Defensor", info: "Lateral derecho de gran regularidad durante todo el torneo." },
            { num: "2", name: "José María Rozzi", pos: "Defensor", info: "Zaguero central que aportó solidez en la final." },
            { num: "6", name: "Marcelino Galoppo", pos: "Defensor", info: "Defensor central de gran temperamento y juego aéreo." },
            { num: "3", name: "Horacio Humoller", pos: "Defensor", info: "Lateral izquierdo de enorme jerarquía y experiencia." },
            { num: "5", name: "Fernando Clementz", pos: "Mediocampista", info: "Volante central de contención táctica y despliegue." },
            { num: "8", name: "Javier Villarreal", pos: "Mediocampista", info: "La joya de la cantera; motor del mediocampo albiazul." },
            { num: "10", name: "Daniel Albornos", pos: "Mediocampista", info: "La 'Chanchita'; habilidad pura y desequilibrio individual." },
            { num: "7", name: "Diego Garay", pos: "Mediocampista", info: "El gran ídolo; el cerebro y conductor del equipo campeón." },
            { num: "9", name: "José 'Cachi' Zelaya", pos: "Delantero", info: "Goleador letal que fue fundamental en toda la campaña." },
            { num: "11", name: "Ramón Medina Bello", pos: "Delantero", info: "El 'Mencho'; potencia de Selección para el ataque matador." },
            { num: "12", name: "Rodrigo Burela", pos: "Arquero", info: "Arquero suplente con mucha seguridad técnica." },
            { num: "14", name: "Andrés Cabrera", pos: "Mediocampista", info: "Volante de marca y relevos fundamentales en el medio." },
            { num: "16", name: "Roberto Oste", pos: "Delantero", info: "El 'Lute'; autor del penal decisivo que marcó la historia." },
            { num: "17", name: "Ramón Galarza", pos: "Defensor", info: "Aportó seguridad defensiva cada vez que le tocó ingresar." },
            { num: "15", name: "Gustavo Lillo", pos: "Defensor/Mediocampista", info: "Polifuncional que fue rueda de auxilio en varios puestos." },
            { num: "18", name: "José Tiburcio Serrizuela", pos: "Defensor", info: "El 'Tiburón'; la jerarquía mundialista en la defensa." }
        ]
    },
    1999: {
        hito: "Campeón Copa CONMEBOL. Único título internacional. DT: Ricardo Gareca.",
        torneo: "Copa Conmebol 1999",
        plantel: [
            { num: "1", name: "Mario Cuenca", pos: "Arquero", info: "Capitán y figura. Héroe en la final." },
            { num: "12", name: "Jorge Ciancaglini", pos: "Arquero", info: "Arquero suplente." },
            { num: "25", name: "Hernán Panero", pos: "Arquero", info: "Tercer arquero." },
            { num: "4", name: "David Díaz", pos: "Defensor", info: "Lateral derecho titular en la final." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Zaguero central. Gol del título." },
            { num: "13", name: "Cristian García", pos: "Defensor", info: "Zaguero central titular en la final." },
            { num: "20", name: "Horacio Humoller", pos: "Defensor", info: "Lateral izquierdo. Referente." },
            { num: "6", name: "Víctor Sotomayor", pos: "Defensor", info: "Zaguero central suplente." },
            { num: "14", name: "Gustavo Lillo", pos: "Defensor", info: "Defensor polivalente." },
            { num: "15", name: "Silvio Suárez", pos: "Defensor", info: "Defensor del plantel campeón." },
            { num: "18", name: "Marcos Morell", pos: "Defensor", info: "Lateral." },
            { num: "19", name: "Santiago Del Sotto", pos: "Defensor", info: "Defensor." },
            { num: "5", name: "Adrián Ávalos", pos: "Mediocampista", info: "Volante central titular en la final." },
            { num: "3", name: "Gabriel Roth", pos: "Mediocampista", info: "Motor del equipo. Titular en la final." },
            { num: "11", name: "Manuel Santos Aguilar", pos: "Mediocampista", info: "Volante titular en la final." },
            { num: "8", name: "Cristian Pino", pos: "Mediocampista", info: "Volante. Clave en semis." },
            { num: "10", name: "Andrés Cabrera", pos: "Mediocampista", info: "Volante de contención." },
            { num: "17", name: "Marcelo Sarmiento", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "21", name: "Fernando Oliva", pos: "Mediocampista", info: "Mediocampista." },
            { num: "23", name: "Ricardo Silva", pos: "Delantero", info: "Delantero titular en la final." },
            { num: "7", name: "Rodrigo Astudillo", pos: "Delantero", info: "El Potro. Titular en la final." },
            { num: "9", name: "Darío Gigena", pos: "Delantero", info: "Goleador del torneo (5 goles)." },
            { num: "16", name: "José Luis Marzo", pos: "Delantero", info: "El Loco. Atacante." },
            { num: "22", name: "Sebastián Flores Coronel", pos: "Delantero", info: "Delantero del plantel campeón." },
            { num: "-", name: "Ricardo Gareca", pos: "Director Técnico", info: "DT campeón. Futuro DT de Perú." }
        ]
    },
    2000: {
        hito: "4° en el Apertura. Talleres protagonista. DT: Ricardo Gareca.",
        torneo: "Apertura 2000 / Clausura 2001",
        plantel: [
            { num: "1", name: "Mario Cuenca", pos: "Arquero", info: "Capitán y referente." },
            { num: "12", name: "Jorge Ciancaglini", pos: "Arquero", info: "Arquero suplente." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Zaguero central titular." },
            { num: "6", name: "Víctor Sotomayor", pos: "Defensor", info: "Zaguero de experiencia." },
            { num: "4", name: "Christian Manfredi", pos: "Defensor", info: "Lateral derecho." },
            { num: "3", name: "Horacio Humoller", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "14", name: "Gustavo Lillo", pos: "Defensor", info: "Defensor polifuncional." },
            { num: "5", name: "Adrián Ávalos", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Cristian Pino", pos: "Mediocampista", info: "Volante." },
            { num: "10", name: "Diego Garay", pos: "Mediocampista", info: "El 10 del equipo." },
            { num: "7", name: "Rodrigo Astudillo", pos: "Delantero", info: "El Potro." },
            { num: "9", name: "Luis Rueda", pos: "Delantero", info: "Goleador." },
            { num: "11", name: "Daniel Albornos", pos: "Mediocampista", info: "La Chanchita." },
            { num: "20", name: "Mariano Monrroy", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "19", name: "Pablo Cuba", pos: "Delantero", info: "Delantero de área." },
            { num: "16", name: "Gabriel Roth", pos: "Mediocampista", info: "Volante." }
        ]
    },
    2001: {
        hito: "Clasificación a Copa Libertadores por primera vez. DT: Mario Zanabria.",
        torneo: "Apertura 2001 / Clausura 2002",
        plantel: [
            { num: "1", name: "Mario Cuenca", pos: "Arquero", info: "Referente máximo." },
            { num: "12", name: "Cristian Muñoz", pos: "Arquero", info: "El Tigre." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Zaguero titular." },
            { num: "6", name: "Víctor Sotomayor", pos: "Defensor", info: "Zaguero central." },
            { num: "4", name: "Christian Manfredi", pos: "Defensor", info: "Lateral derecho." },
            { num: "3", name: "Víctor López", pos: "Defensor", info: "Zaguero joven." },
            { num: "5", name: "Adrián Ávalos", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Gabriel Roth", pos: "Mediocampista", info: "Motor del equipo." },
            { num: "10", name: "César La Paglia", pos: "Mediocampista", info: "El Leche. Talento." },
            { num: "7", name: "Diego Garay", pos: "Mediocampista", info: "Ídolo." },
            { num: "9", name: "Federico Astudillo", pos: "Delantero", info: "Goleador." },
            { num: "11", name: "Pablo Cuba", pos: "Delantero", info: "Atacante." },
            { num: "14", name: "Marcelo Sarmiento", pos: "Mediocampista", info: "Volante." },
            { num: "15", name: "Santiago Del Sotto", pos: "Defensor", info: "Defensor." },
            { num: "16", name: "Cristian Pino", pos: "Mediocampista", info: "Volante." }
        ]
    },
    2002: {
        hito: "Debut en Copa Libertadores de América. DT: Mario Zanabria.",
        torneo: "Copa Libertadores 2002",
        plantel: [
            { num: "1", name: "Mario Cuenca", pos: "Arquero", info: "Histórico arquero." },
            { num: "12", name: "Cristian Muñoz", pos: "Arquero", info: "El Tigre." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Líder de la defensa." },
            { num: "6", name: "Víctor Sotomayor", pos: "Defensor", info: "Veterano internacional." },
            { num: "4", name: "Cristian Manfredi", pos: "Defensor", info: "Lateral derecho." },
            { num: "3", name: "Víctor López", pos: "Defensor", info: "Zaguero zurdo." },
            { num: "14", name: "Gustavo Lillo", pos: "Defensor", info: "Defensor." },
            { num: "5", name: "Jorge Carrizo", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Gabriel Roth", pos: "Mediocampista", info: "Motor." },
            { num: "10", name: "Diego Garay", pos: "Mediocampista", info: "El 10 de la Copa." },
            { num: "7", name: "César La Paglia", pos: "Mediocampista", info: "Enganche." },
            { num: "20", name: "Mariano Monrroy", pos: "Mediocampista", info: "Talento." },
            { num: "9", name: "Federico Astudillo", pos: "Delantero", info: "Atacante." },
            { num: "19", name: "Pablo Cuba", pos: "Delantero", info: "Goleador en la Copa." },
            { num: "11", name: "Eber Fernández", pos: "Delantero", info: "Delantero." },
            { num: "15", name: "Ramón Galarza", pos: "Defensor", info: "Lateral." }
        ]
    },
    2003: {
        hito: "Salvación en Promoción ante San Martín (Mza).",
        torneo: "Apertura / Clausura 2003",
        plantel: [
            { num: "1", name: "Marcos Gutiérrez", pos: "Arquero", info: "La Anguila. Titular." },
            { num: "12", name: "Luis Islas", pos: "Arquero", info: "Experiencia internacional." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Zaguero referente." },
            { num: "4", name: "Christian Manfredi", pos: "Defensor", info: "Lateral derecho." },
            { num: "6", name: "Víctor López", pos: "Defensor", info: "Zaguero zurdo." },
            { num: "3", name: "Andrés Bressán", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Ramón Galarza", pos: "Defensor", info: "Marcador central." },
            { num: "8", name: "Maximiliano Salas", pos: "Mediocampista", info: "Volante central clave." },
            { num: "10", name: "Diego Garay", pos: "Mediocampista", info: "El 10 del equipo." },
            { num: "7", name: "Luciano De Bruno", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "9", name: "Pablo Cuba", pos: "Delantero", info: "Goleador del equipo." },
            { num: "11", name: "Víctor Píriz Álvez", pos: "Delantero", info: "Uruguayo. Goleador." },
            { num: "14", name: "Ariel Donnet", pos: "Mediocampista", info: "Volante." },
            { num: "15", name: "Mauricio Serna", pos: "Mediocampista", info: "Chicho. Jerarquía." },
            { num: "16", name: "Facundo Erpen", pos: "Defensor", info: "Zaguero central joven." }
        ]
    },
    2004: {
        hito: "La paradoja del fútbol: Talleres termina 3° en el Clausura pero desciende por el sistema de promedios.",
        torneo: "Clausura 2004",
        plantel: [
            { num: "1", name: "Marcos Gutiérrez", pos: "Arquero", info: "La 'Anguila'; arquero de gran nivel que sostuvo el arco con seguridad." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "El gran capitán y líder espiritual de una defensa férrea." },
            { num: "6", name: "Víctor López", pos: "Defensor", info: "Zaguero zurdo de nivel internacional; pilar de la zaga." },
            { num: "4", name: "Ariel Donnet", pos: "Mediocampista/Defensor", info: "Carrilero derecho con mucho ida y vuelta y buen centro." },
            { num: "5", name: "Mauricio Serna", pos: "Mediocampista", info: "El 'Chicho'; jerarquía total en el centro de la cancha." },
            { num: "8", name: "Maximiliano Salas", pos: "Mediocampista", info: "Aportó equilibrio y marca en el doble cinco." },
            { num: "3", name: "Maximiliano Velázquez", pos: "Defensor", info: "Lateral izquierdo de gran proyección y pegada." },
            { num: "10", name: "Luciano De Bruno", pos: "Mediocampista", info: "El enganche; gran visión de juego y llegada al gol." },
            { num: "7", name: "Víctor Píriz Álvez", pos: "Delantero", info: "El uruguayo; potencia física y una fiera en el área rival." },
            { num: "9", name: "Aldo Osorio", pos: "Delantero", info: "Goleador del equipo en una campaña inolvidable pero triste." },
            { num: "12", name: "Marcos Argüello", pos: "Arquero", info: "Arquero suplente formado en el club." },
            { num: "14", name: "Facundo Erpen", pos: "Defensor", info: "Zaguero central joven que demostró gran potencial." },
            { num: "15", name: "Emanuel Giménez", pos: "Mediocampista", info: "Volante central de recambio con buen manejo." },
            { num: "11", name: "Juan Pablo Avendaño", pos: "Defensor", info: "Aportó seguridad defensiva cada vez que fue requerido." },
            { num: "17", name: "Sebastián Carrizo", pos: "Mediocampista", info: "Volante central de marca y despliegue físico." }
        ]
    },
    2005: {
        hito: "Descenso a la B Nacional tras Promoción con Argentinos Jrs. DT: J. J. López.",
        torneo: "Primera División 2004/05",
        plantel: [
            { num: "1", name: "Marcos Gutiérrez", pos: "Arquero", info: "La Anguila." },
            { num: "12", name: "Marcos Argüello", pos: "Arquero", info: "Suplente." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Capitán histórico." },
            { num: "6", name: "Víctor López", pos: "Defensor", info: "Zaguero central." },
            { num: "3", name: "Facundo Erpen", pos: "Defensor", info: "Zaguero central." },
            { num: "4", name: "Mariano Córsico", pos: "Defensor", info: "Lateral derecho." },
            { num: "5", name: "Mauricio Serna", pos: "Mediocampista", info: "Chicho. Últimos partidos en el club." },
            { num: "8", name: "Maximiliano Salas", pos: "Mediocampista", info: "Referente del equipo." },
            { num: "10", name: "Luciano De Bruno", pos: "Mediocampista", info: "Enganche goleador." },
            { num: "7", name: "Víctor Píriz Álvez", pos: "Delantero", info: "Uruguayo. Figura." },
            { num: "9", name: "Aldo Osorio", pos: "Delantero", info: "Goleador del equipo." },
            { num: "11", name: "Pablo Cuba", pos: "Delantero", info: "Atacante." },
            { num: "14", name: "Emanuel Giménez", pos: "Mediocampista", info: "Volante central." },
            { num: "15", name: "Ezequiel Lázaro", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "16", name: "Sebastián Carrizo", pos: "Mediocampista", info: "Volante de marca." }
        ]
    },
    2006: {
        hito: "B Nacional 05/06. Talleres pelea el ascenso con Saporiti.",
        torneo: "Primera B Nacional 2005/06",
        plantel: [
            { num: "1", name: "Diego Pozo", pos: "Arquero", info: "Seguridad bajo los tres palos." },
            { num: "12", name: "Silvio Dulcich", pos: "Arquero", info: "Arquero suplente." },
            { num: "2", name: "Javier Malagueño", pos: "Defensor", info: "Zaguero central de jerarquía." },
            { num: "6", name: "Gabriel Oyola", pos: "Defensor", info: "Central surgido del club." },
            { num: "4", name: "Renzo Vera", pos: "Defensor", info: "Defensor central sólido." },
            { num: "3", name: "Leonardo Baroni", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Emanuel Giménez", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Damián Felicia", pos: "Mediocampista", info: "Volante de marca y juego." },
            { num: "10", name: "Cristian Zermatten", pos: "Mediocampista", info: "El cerebro del equipo." },
            { num: "7", name: "Luciano Leguizamón", pos: "Delantero", info: "Talento y goles decisivos." },
            { num: "9", name: "Silvio Carrario", pos: "Delantero", info: "El Tweety. Goleador trotamundos." },
            { num: "11", name: "Ezequiel Lázaro", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "14", name: "Darío Gigena", pos: "Delantero", info: "El Topo. Goleador." },
            { num: "15", name: "Agustín Correa", pos: "Mediocampista", info: "Volante central." },
            { num: "16", name: "Matías Quiroga", pos: "Mediocampista", info: "Volante carrilero." }
        ]
    },
    2007: {
        hito: "Talleres en la B Nacional. DT: Ricardo Gareca / Salvador Capitano.",
        torneo: "Primera B Nacional 2006/07",
        plantel: [
            { num: "1", name: "Valentín Brasca", pos: "Arquero", info: "Arrancó como titular." },
            { num: "12", name: "Diego Pozo", pos: "Arquero", info: "Experiencia en el arco." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Regresó como caudillo." },
            { num: "6", name: "Juan Cruz Gill", pos: "Defensor", info: "Zaguero central." },
            { num: "4", name: "Joel Barbosa", pos: "Defensor", info: "Lateral derecho." },
            { num: "3", name: "Marco Torsiglieri", pos: "Defensor", info: "Paso por el club." },
            { num: "5", name: "Iván Borghello", pos: "Delantero", info: "El Memo. Goleador." },
            { num: "8", name: "Matías Quiroga", pos: "Mediocampista", info: "Volante por izquierda." },
            { num: "10", name: "Julio Buffarini", pos: "Mediocampista", info: "Sus inicios. Mucha garra." },
            { num: "7", name: "Héctor Cuevas", pos: "Delantero", info: "El Tanque." },
            { num: "9", name: "Víctor Píriz Álvez", pos: "Delantero", info: "La Fiera regresó." },
            { num: "11", name: "Ezequiel Lázaro", pos: "Mediocampista", info: "Enganche." },
            { num: "14", name: "Damián Felicia", pos: "Mediocampista", info: "Volante." },
            { num: "15", name: "Agustín Correa", pos: "Mediocampista", info: "Recambio en el medio." },
            { num: "16", name: "Leonardo Baroni", pos: "Defensor", info: "Lateral izquierdo." }
        ]
    },
    2008: {
        hito: "El Talleres de Ahumada. Grandes figuras, triste final.",
        torneo: "Primera B Nacional 2007/08",
        plantel: [
            { num: "1", name: "Valentín Brasca", pos: "Arquero", info: "Arquero titular." },
            { num: "12", name: "Marcos Argüello", pos: "Arquero", info: "Alternativa." },
            { num: "2", name: "Federico Lussenhoff", pos: "Defensor", info: "El Colorado. Jerarquía europea." },
            { num: "6", name: "Gastón Stang", pos: "Defensor", info: "Zaguero central." },
            { num: "4", name: "Juan José Serrizuela", pos: "Defensor", info: "Lateral derecho. Experiencia." },
            { num: "3", name: "Edgardo Galíndez", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Cristian Zermatten", pos: "Mediocampista", info: "Volante central clave." },
            { num: "8", name: "Julio Buffarini", pos: "Mediocampista", info: "Consolidado en el equipo." },
            { num: "10", name: "Lucas Wilchez", pos: "Mediocampista", info: "El enganche habilidoso." },
            { num: "7", name: "Luis Salmerón", pos: "Delantero", info: "El Pupi. Goleador del equipo." },
            { num: "9", name: "Héctor Cuevas", pos: "Delantero", info: "Delantero de área." },
            { num: "11", name: "Sebastián Cobelli", pos: "Delantero", info: "Atacante experimentado." },
            { num: "14", name: "Celso Esquivel", pos: "Defensor", info: "Lateral paraguayo." },
            { num: "15", name: "Robert Moreira Aldana", pos: "Delantero", info: "Atacante." },
            { num: "16", name: "Cristian Pino", pos: "Mediocampista", info: "Volante." }
        ]
    },
    2009: {
        hito: "Descenso al Argentino A. Punto más bajo. DT: Juan Amador Sánchez.",
        torneo: "Primera B Nacional 2008/09",
        plantel: [
            { num: "1", name: "Valentín Brasca", pos: "Arquero", info: "Responsabilidad en el arco." },
            { num: "2", name: "Julián Maidana", pos: "Defensor", info: "Última etapa en el club." },
            { num: "6", name: "Federico Lussenhoff", pos: "Defensor", info: "Caudillo defensivo." },
            { num: "4", name: "Gastón Stang", pos: "Defensor", info: "Zaguero." },
            { num: "3", name: "Edgardo Galíndez", pos: "Defensor", info: "Fuerza defensiva." },
            { num: "5", name: "Cristian Zermatten", pos: "Mediocampista", info: "Eje del equipo." },
            { num: "8", name: "Julio Buffarini", pos: "Mediocampista", info: "Uno de los pocos rescatables." },
            { num: "10", name: "Lucas Wilchez", pos: "Mediocampista", info: "Talento solitario." },
            { num: "7", name: "Luis Salmerón", pos: "Delantero", info: "Goleador del descenso (18 goles)." },
            { num: "9", name: "Héctor Cuevas", pos: "Delantero", info: "Atacante." },
            { num: "11", name: "Sebastián Cobelli", pos: "Delantero", info: "Delantero." },
            { num: "14", name: "Juan José Serrizuela", pos: "Defensor", info: "Lateral." },
            { num: "15", name: "Pablo Dante Azcurra", pos: "Mediocampista", info: "Volante." },
            { num: "16", name: "Roberto Ramón Moreira Aldana", pos: "Delantero", info: "Atacante paraguayo." },
            { num: "17", name: "José Ramiro Pereyra", pos: "Delantero", info: "El Rama." }
        ]
    },
    2010: {
        hito: "Primer año en el Argentino A. Dolorosa adaptación. DT: Andrés Rebottaro.",
        torneo: "Torneo Argentino A 2009/10",
        plantel: [
            { num: "1", name: "Matías Giordano", pos: "Arquero", info: "Arquero experimentado." },
            { num: "12", name: "Leandro Requena", pos: "Arquero", info: "Juvenil." },
            { num: "2", name: "Federico Lussenhoff", pos: "Defensor", info: "Se quedó para el Argentino A." },
            { num: "6", name: "Ricardo Marín", pos: "Defensor", info: "Zaguero central." },
            { num: "4", name: "Ignacio González Barón", pos: "Defensor", info: "Lateral." },
            { num: "3", name: "Edgardo Galíndez", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Sebastián Navarro", pos: "Mediocampista", info: "Volante central clave." },
            { num: "8", name: "Émiliano Ciucci", pos: "Mediocampista", info: "Esfuerzo en el medio." },
            { num: "10", name: "Agustín Díaz", pos: "Mediocampista", info: "El Tin. Talento puro." },
            { num: "7", name: "Ramiro Pereyra", pos: "Delantero", info: "El Rama." },
            { num: "9", name: "Adrián Aranda", pos: "Delantero", info: "El Bati. Goleador." },
            { num: "11", name: "Claudio Riaño", pos: "Delantero", info: "Llegó de Las Palmas. Gran debut." },
            { num: "14", name: "Emiliano Gianunzio", pos: "Mediocampista", info: "Capitán del equipo." },
            { num: "15", name: "Nery Leyes", pos: "Mediocampista", info: "Volante central." },
            { num: "16", name: "Gabriel Carabajal", pos: "Mediocampista", info: "Juvenil promesa." }
        ]
    },
    2011: {
        hito: "Talleres lucha en el Argentino A. DT: Arnaldo Sialle.",
        torneo: "Torneo Argentino A 2011/12",
        plantel: [
            { num: "1", name: "Michael Etulain", pos: "Arquero", info: "Experiencia en el arco." },
            { num: "12", name: "Leandro Requena", pos: "Arquero", info: "Alternativa confiable." },
            { num: "2", name: "Nicolás Romat", pos: "Defensor", info: "Zaguero central." },
            { num: "6", name: "Guillermo Cosaro", pos: "Defensor", info: "Defensor polifuncional." },
            { num: "4", name: "Nicolás Ballestero", pos: "Defensor", info: "Zaguero fuerte." },
            { num: "3", name: "Walter Ledesma", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Emiliano Gianunzio", pos: "Mediocampista", info: "Capitán del equipo." },
            { num: "8", name: "Nery Leyes", pos: "Mediocampista", info: "Volante central." },
            { num: "10", name: "Agustín Díaz", pos: "Mediocampista", info: "El Tin. Eje del juego." },
            { num: "11", name: "Gabriel Carabajal", pos: "Mediocampista", info: "La joya desequilibrante." },
            { num: "7", name: "José Ramiro Pereyra", pos: "Delantero", info: "Atacante habilidoso." },
            { num: "9", name: "Claudio Riaño", pos: "Delantero", info: "Goleador del equipo (15 goles)." },
            { num: "14", name: "Favio Álvarez", pos: "Mediocampista", info: "Talento juvenil." },
            { num: "15", name: "Sebastián Sáez", pos: "Delantero", info: "El Sacha. Goleador." },
            { num: "16", name: "Román Strada", pos: "Mediocampista", info: "Volante ofensivo." }
        ]
    },
    2012: {
        hito: "Campeón Octogonal Argentino A. Ascenso al Nacional B. DT: Cacho Sialle.",
        torneo: "Torneo Argentino A 2012/13",
        plantel: [
            { num: "1", name: "Diego Aguiar", pos: "Arquero", info: "Arquero del ascenso." },
            { num: "12", name: "Leandro Requena", pos: "Arquero", info: "Suplente." },
            { num: "2", name: "Jesús Nievas", pos: "Defensor", info: "La Gringa. Caudillo." },
            { num: "6", name: "Juan Rezzónico", pos: "Defensor", info: "Zaguero fuerte." },
            { num: "4", name: "Rodrigo Cháves", pos: "Defensor", info: "Lateral derecho." },
            { num: "3", name: "Nelson Benítez", pos: "Defensor", info: "Lateral de jerarquía." },
            { num: "5", name: "Javier Villarreal", pos: "Mediocampista", info: "Regresó del retiro para el ascenso." },
            { num: "8", name: "Gastón Bottino", pos: "Mediocampista", info: "El autor del gol a Belgrano." },
            { num: "10", name: "Agustín Díaz", pos: "Mediocampista", info: "El Tin. Referente." },
            { num: "11", name: "Gabriel Carabajal", pos: "Mediocampista", info: "Figura ofensiva." },
            { num: "9", name: "Gonzalo Klusener", pos: "Delantero", info: "Goleador histórico (25 goles)." },
            { num: "7", name: "Franco Olego", pos: "Delantero", info: "Atacante veloz." },
            { num: "14", name: "Favio Álvarez", pos: "Mediocampista", info: "Promesa local." },
            { num: "15", name: "Marcos Brítez Ojeda", pos: "Mediocampista", info: "Jerarquía en el medio." },
            { num: "16", name: "Elías Bazzi", pos: "Defensor", info: "Defensor experimentado." }
        ]
    },
    2013: {
        hito: "Ascenso al Nacional B. Centenario del club. DT: Cacho Sialle.",
        torneo: "Torneo Argentino A 2012/13",
        plantel: [
            { num: "1", name: "Diego Aguiar", pos: "Arquero", info: "Arquero titular del ascenso." },
            { num: "12", name: "Leandro Requena", pos: "Arquero", info: "Arquero suplente." },
            { num: "25", name: "Federico Costa", pos: "Arquero", info: "Tercer arquero." },
            { num: "4", name: "Rodrigo Cháves", pos: "Defensor", info: "Lateral derecho." },
            { num: "2", name: "Jesús Nievas", pos: "Defensor", info: "La Gringa. Zaguero." },
            { num: "6", name: "Elías Bazzi", pos: "Defensor", info: "Zaguero central." },
            { num: "3", name: "Nelson Benítez", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "13", name: "Ezequiel Brítez", pos: "Defensor", info: "Defensor." },
            { num: "16", name: "Diego Chitzoff", pos: "Defensor", info: "Defensor central." },
            { num: "18", name: "Jorge Massena", pos: "Defensor", info: "Defensor." },
            { num: "5", name: "Javier Villarreal", pos: "Mediocampista", info: "Capitán. Se retiró campeón." },
            { num: "8", name: "Gastón Bottino", pos: "Mediocampista", info: "Gol a Belgrano y ascenso." },
            { num: "10", name: "Agustín Díaz", pos: "Mediocampista", info: "El Tin. Talento local." },
            { num: "11", name: "Gabriel Carabajal", pos: "Mediocampista", info: "Desequilibrio." },
            { num: "15", name: "Nery Leyes", pos: "Mediocampista", info: "Volante central." },
            { num: "14", name: "Marcos Brítez Ojeda", pos: "Mediocampista", info: "Volante." },
            { num: "20", name: "Favio Álvarez", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "17", name: "Hernán Becica", pos: "Mediocampista", info: "Mediocampista." },
            { num: "19", name: "Horacio Carabajal", pos: "Mediocampista", info: "Volante." },
            { num: "9", name: "Gonzalo Klusener", pos: "Delantero", info: "Goleador: 25 goles. Máximo del torneo." },
            { num: "7", name: "Maximiliano Velasco", pos: "Delantero", info: "Gol del ascenso con taco." },
            { num: "21", name: "Franco Olego", pos: "Delantero", info: "Delantero." },
            { num: "23", name: "Ivo Hongn", pos: "Delantero", info: "Atacante." },
            { num: "22", name: "Miguel Olivera", pos: "Delantero", info: "Delantero." },
            { num: "-", name: "Arnaldo Sialle", pos: "Director Técnico", info: "Cacho. DT del ascenso centenario." }
        ]
    },
    2014: {
        hito: "Campaña en el Federal A tras el rápido descenso. DT: Ángel Hoyos.",
        torneo: "Torneo Federal A 2014",
        plantel: [
            { num: "1", name: "Federico Costa", pos: "Arquero", info: "Arquero titular." },
            { num: "12", name: "Danilo Lerda", pos: "Arquero", info: "Alternativa." },
            { num: "2", name: "Lucas Bovaglio", pos: "Defensor", info: "Zaguero central de jerarquía." },
            { num: "6", name: "Rodrigo López", pos: "Defensor", info: "Defensor central." },
            { num: "4", name: "Rodrigo Cháves", pos: "Defensor", info: "Lateral derecho." },
            { num: "3", name: "Lautaro Formica", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Julio Mozzo", pos: "Mediocampista", info: "Volante central uruguayo." },
            { num: "8", name: "Agustín Díaz", pos: "Mediocampista", info: "Referente del mediocampo." },
            { num: "10", name: "Víctor Beraldi", pos: "Mediocampista", info: "Enganche habilidoso." },
            { num: "7", name: "Gabriel Carabajal", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "9", name: "Diego Martínez", pos: "Delantero", info: "Goleador del equipo." },
            { num: "11", name: "Marcos Godoy", pos: "Delantero", info: "Atacante." },
            { num: "14", name: "Nicolás Schenone Paz", pos: "Mediocampista", info: "Mediocampista uruguayo." },
            { num: "15", name: "Ezequiel Barrionuevo", pos: "Mediocampista", info: "El Indio." },
            { num: "16", name: "Ivo Cháves", pos: "Defensor", info: "Lateral derecho." },
            { num: "17", name: "Nelson Benítez", pos: "Defensor", info: "Lateral izquierdo." }
        ]
    },
    2015: {
        hito: "Ascenso Invicto a la B Nacional. DT: Frank Kudelka.",
        torneo: "Torneo Federal A 2015",
        plantel: [
            { num: "1", name: "Lucas Ischuk", pos: "Arquero", info: "Arquero del ascenso." },
            { num: "12", name: "Federico Costa", pos: "Arquero", info: "Suplente." },
            { num: "2", name: "Wilfredo Olivera", pos: "Defensor", info: "El Willy. Gol del ascenso." },
            { num: "6", name: "Adalberto Goiri", pos: "Defensor", info: "Zaguero central paraguayo." },
            { num: "4", name: "Ivo Cháves", pos: "Defensor", info: "Lateral derecho dinámico." },
            { num: "3", name: "Nelson Benítez", pos: "Defensor", info: "Capitán del ascenso." },
            { num: "5", name: "Rodrigo Burgos", pos: "Mediocampista", info: "El León paraguayo. Ídolo." },
            { num: "8", name: "Santiago Raymonda", pos: "Mediocampista", info: "El Pato. Jerarquía pura." },
            { num: "10", name: "Juan Pablo Francia", pos: "Mediocampista", info: "Talento y pausa." },
            { num: "11", name: "Aldo Araujo", pos: "Mediocampista", info: "Turbina. Desequilibrio total." },
            { num: "7", name: "Victorio Ramis", pos: "Delantero", info: "Pipe. Gol del campeonato." },
            { num: "9", name: "Eial Strahman", pos: "Delantero", info: "Goleador del equipo (14 goles)." },
            { num: "15", name: "Víctor Beraldi", pos: "Mediocampista", info: "Volante ofensivo." },
            { num: "14", name: "Javier Velázquez", pos: "Delantero", info: "Atacante de área." },
            { num: "16", name: "Marcos Godoy", pos: "Delantero", info: "Delantero." },
            { num: "17", name: "Ezequiel Barrionuevo", pos: "Mediocampista", info: "Extremo." }
        ]
    },
    2016: {
        hito: "Campeón Invicto de la B Nacional: El histórico gol del 'Cholo' Guiñazú ante All Boys devolvió a Talleres a Primera.",
        torneo: "B Nacional 2016",
        plantel: [
            { num: "1", name: "Guido Herrera", pos: "Arquero", info: "Se ganó la titularidad y mantuvo el arco invicto por 701 minutos." },
            { num: "22", name: "Mauricio Caranta", pos: "Arquero", info: "Referente absoluto y líder del vestuario campeón." },
            { num: "4", name: "Ivo Cháves", pos: "Defensor", info: "Lateral derecho de gran proyección y entrega constante." },
            { num: "2", name: "Wilfredo Olivera", pos: "Defensor", info: "El 'Willy'; baluarte de la defensa y firme en el juego aéreo." },
            { num: "6", name: "Carlos Quintana", pos: "Defensor", info: "El 'Pelado'; una muralla impasable en la zaga central." },
            { num: "13", name: "Juan Cruz Komar", pos: "Defensor", info: "Juvenil consolidado con gran lectura de juego." },
            { num: "5", name: "Pablo Guiñazú", pos: "Mediocampista", info: "El 'Cholo'; autor del gol más importante de los últimos años." },
            { num: "8", name: "Rodrigo Burgos", pos: "Mediocampista", info: "El 'León' paraguayo; ídolo por su garra y despliegue." },
            { num: "10", name: "Emanuel Reynoso", pos: "Mediocampista", info: "La joya de la cantera que deslumbró con su talento." },
            { num: "11", name: "Nazareno Solís", pos: "Delantero", info: "Figura y máximo asistidor del equipo campeón." },
            { num: "9", name: "Gonzalo Klusener", pos: "Delantero", info: "El goleador histórico que regresó para ser campeón." },
            { num: "16", name: "Eial Strahman", pos: "Delantero", info: "Aportó goles fundamentales en momentos decisivos." },
            { num: "7", name: "Victorio Ramis", pos: "Delantero", info: "El 'Pipe'; formado en el club, siempre importante en ofensiva." },
            { num: "18", name: "Luis Jerez Silva", pos: "Mediocampista", info: "Aportó equilibrio en la mitad de la cancha cada vez que jugó." },
            { num: "3", name: "David Achucarro", pos: "Defensor", info: "Lateral izquierdo que brindó seguridad defensiva." }
        ]
    },
    2017: {
        hito: "Regreso a Primera División tras 12 años. Gran campaña. DT: Frank Kudelka.",
        torneo: "Primera División 2016/17",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Figura indiscutida." },
            { num: "1", name: "Mauricio Caranta", pos: "Arquero", info: "Suplente de lujo." },
            { num: "4", name: "Leonardo Godoy", pos: "Defensor", info: "Consolidado lateral derecho." },
            { num: "2", name: "Juan Cruz Komar", pos: "Defensor", info: "Zaguero central titular." },
            { num: "6", name: "Javier Gandolfi", pos: "Defensor", info: "El capitán. Regresó para Primera." },
            { num: "13", name: "Carlos Quintana", pos: "Defensor", info: "Defensor central." },
            { num: "3", name: "Ian Escobar", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Pablo Guiñazú", pos: "Mediocampista", info: "El Cholo. Motor del equipo." },
            { num: "10", name: "Emanuel Reynoso", pos: "Mediocampista", info: "Bebelo. La magia." },
            { num: "8", name: "Leonardo Gil", pos: "Mediocampista", info: "El Colo. Pegada exquisita." },
            { num: "21", name: "Sebastián Palacios", pos: "Delantero", info: "Goleador del equipo (9 goles)." },
            { num: "7", name: "Victorio Ramis", pos: "Delantero", info: "Pipe. Atacante." },
            { num: "9", name: "Gonzalo Klusener", pos: "Delantero", info: "Su última etapa en el club." },
            { num: "11", name: "Jonathan Menéndez", pos: "Delantero", info: "Extremo veloz." },
            { num: "20", name: "Aldo Araujo", pos: "Mediocampista", info: "Turbina." },
            { num: "14", name: "Fernando Godoy", pos: "Mediocampista", info: "Volante de marca." }
        ]
    },
    2018: {
        hito: "Clasificación a Copa Libertadores tras 17 años. La era Kudelka llega a su fin.",
        torneo: "Superliga 2017/18",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Arquero récord y capitán." },
            { num: "1", name: "Mauricio Caranta", pos: "Arquero", info: "Voz de mando en el vestuario." },
            { num: "4", name: "Leonardo Godoy", pos: "Defensor", info: "Lateral derecho de gran proyección." },
            { num: "6", name: "Juan Cruz Komar", pos: "Defensor", info: "Zaguero central de calidad." },
            { num: "2", name: "Javier Gandolfi", pos: "Defensor", info: "Capitán y referente histórico." },
            { num: "13", name: "Carlos Quintana", pos: "Defensor", info: "Zaguero central sólido." },
            { num: "14", name: "Nahuel Tenaglia", pos: "Defensor", info: "Defensor polifuncional." },
            { num: "3", name: "Ian Escobar", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "5", name: "Pablo Guiñazú", pos: "Mediocampista", info: "El Cholo. El alma del equipo." },
            { num: "8", name: "Juan Ramírez", pos: "Mediocampista", info: "Volante mixto de gran manejo." },
            { num: "10", name: "Emanuel Reynoso", pos: "Mediocampista", info: "Bebelo. El 10 talentoso." },
            { num: "15", name: "Fernando Godoy", pos: "Mediocampista", info: "Volante de marca." },
            { num: "7", name: "Jonathan Menéndez", pos: "Delantero", info: "Extremo veloz." },
            { num: "11", name: "Aldo Araujo", pos: "Delantero", info: "Turbina. Desequilibrio." },
            { num: "9", name: "Marcelo Torres", pos: "Delantero", info: "El Chelo. Atacante potente." },
            { num: "40", name: "Joaquín Blázquez", pos: "Arquero", info: "Arquero juvenil de Selección." }
        ]
    },
    2019: {
        hito: "Histórica victoria ante São Paulo en Copa Libertadores. El equipo de Vojvoda.",
        torneo: "Copa Libertadores / Superliga 2018/19",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Líder del arco matador." },
            { num: "1", name: "Mauricio Caranta", pos: "Arquero", info: "Experiencia acumulada." },
            { num: "4", name: "Leonardo Godoy", pos: "Defensor", info: "Lateral derecho de gran despliegue." },
            { num: "6", name: "Juan Cruz Komar", pos: "Defensor", info: "Caudillo de la zaga central." },
            { num: "2", name: "Javier Gandolfi", pos: "Defensor", info: "Referente ineludible." },
            { num: "15", name: "Enzo Díaz", pos: "Defensor", info: "Lateral izquierdo. Gran revelación." },
            { num: "14", name: "Nahuel Tenaglia", pos: "Defensor", info: "Zaguero y lateral polivalente." },
            { num: "24", name: "Facundo Medina", pos: "Defensor", info: "Zaguero de proyección internacional." },
            { num: "5", name: "Andrés Cubas", pos: "Mediocampista", info: "Volante central de altísimo nivel." },
            { num: "8", name: "Juan Ignacio Méndez", pos: "Mediocampista", info: "Balance en el medio." },
            { num: "10", name: "Tomás Pochettino", pos: "Mediocampista", info: "Creatividad y gran pegada." },
            { num: "7", name: "Franco Fragapane", pos: "Mediocampista", info: "Goles y asistencia por izquierda." },
            { num: "20", name: "Dayro Moreno", pos: "Delantero", info: "Jerarquía colombiana absoluta." },
            { num: "9", name: "Nahuel Bustos", pos: "Delantero", info: "Juvenil con destino europeo." },
            { num: "11", name: "Sebastian Palacios", pos: "Delantero", info: "El Tucu. Velocidad pura." },
            { num: "17", name: "Jonathan Menéndez", pos: "Delantero", info: "Extremo desequilibrante." },
            { num: "28", name: "Federico Navarro", pos: "Mediocampista", info: "Joven motor del mediocampo." }
        ]
    },
    2020: {
        hito: "Copa Liga Profesional en pandemia. Piero Hincapié y Nahuel Bustos.",
        torneo: "Copa Liga Profesional 2020",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Capitán." },
            { num: "1", name: "Marcos Díaz", pos: "Arquero", info: "Refuerzo." },
            { num: "2", name: "Rafael Pérez", pos: "Defensor", info: "Colombiano titular." },
            { num: "6", name: "Juan Cruz Komar", pos: "Defensor", info: "Zaguero." },
            { num: "4", name: "Piero Hincapié", pos: "Defensor", info: "Vendido a Bayer Leverkusen." },
            { num: "14", name: "Nahuel Tenaglia", pos: "Defensor", info: "Lateral derecho." },
            { num: "15", name: "Enzo Díaz", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "3", name: "Leonardo Godoy", pos: "Defensor", info: "Lateral." },
            { num: "5", name: "Federico Navarro", pos: "Mediocampista", info: "Volante central." },
            { num: "10", name: "Tomás Pochettino", pos: "Mediocampista", info: "Enganche." },
            { num: "7", name: "Diego Valoyes", pos: "Delantero", info: "La Pantera." },
            { num: "28", name: "Carlos Auzqui", pos: "Delantero", info: "El Perro." },
            { num: "9", name: "Nahuel Bustos", pos: "Delantero", info: "Vendido a Girona." },
            { num: "11", name: "Mateo Retegui", pos: "Delantero", info: "Futuro internacional italiano." },
            { num: "18", name: "Rodrigo Villagra", pos: "Mediocampista", info: "Volante central." },
            { num: "21", name: "Ángelo Martino", pos: "Defensor", info: "Lateral izquierdo." }
        ]
    },
    2021: {
        hito: "Final Copa Argentina. Subcampeón Liga. DT: Alexander Medina.",
        torneo: "Liga Profesional 2021",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Capitán." },
            { num: "1", name: "Marcos Díaz", pos: "Arquero", info: "Suplente experimentado." },
            { num: "35", name: "Joaquín Blázquez", pos: "Arquero", info: "Tercer arquero." },
            { num: "14", name: "Nahuel Tenaglia", pos: "Defensor", info: "Lateral derecho. Figura." },
            { num: "2", name: "Rafael Pérez", pos: "Defensor", info: "La Muralla colombiana." },
            { num: "6", name: "Juan Cruz Komar", pos: "Defensor", info: "Referente." },
            { num: "4", name: "Piero Hincapié", pos: "Defensor", info: "Vendido a Bayer Leverkusen." },
            { num: "15", name: "Enzo Díaz", pos: "Defensor", info: "Lateral izquierdo titular." },
            { num: "21", name: "Ángelo Martino", pos: "Defensor", info: "Lateral/Volante izquierdo." },
            { num: "24", name: "Julián Malatini", pos: "Defensor", info: "Defensor central." },
            { num: "3", name: "Federico Torres", pos: "Defensor", info: "Zaguero." },
            { num: "26", name: "Julián Velázquez", pos: "Defensor", info: "Defensor." },
            { num: "5", name: "Federico Navarro", pos: "Mediocampista", info: "Volante central. Vendido a MLS." },
            { num: "18", name: "Rodrigo Villagra", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Juan Ignacio Méndez", pos: "Mediocampista", info: "Volante mixto." },
            { num: "29", name: "Héctor Fértoli", pos: "Mediocampista", info: "Extremo habilidoso." },
            { num: "11", name: "Franco Fragapane", pos: "Mediocampista", info: "Desequilibrio por izquierda." },
            { num: "28", name: "Carlos Auzqui", pos: "Delantero", info: "El Perro. Goleador." },
            { num: "7", name: "Diego Valoyes", pos: "Delantero", info: "La Pantera. Figura." },
            { num: "9", name: "Michael Santos", pos: "Delantero", info: "Goleador uruguayo." },
            { num: "19", name: "Mateo Retegui", pos: "Delantero", info: "Futuro internacional italiano." },
            { num: "77", name: "Guilherme Parede", pos: "Delantero", info: "Brasileño." },
            { num: "30", name: "Francis Mac Allister", pos: "Mediocampista", info: "Volante." },
            { num: "-", name: "Alexander Medina", pos: "Director Técnico", info: "El Cacique. Subcampeón." }
        ]
    },
    2022: {
        hito: "Talleres consolidado en Primera. Competitivo.",
        torneo: "Liga Profesional 2022",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Capitán histórico." },
            { num: "1", name: "Alan Aguerre", pos: "Arquero", info: "Alternativa en el arco." },
            { num: "35", name: "Joaquín Blázquez", pos: "Arquero", info: "Juvenil." },
            { num: "4", name: "Matías Catalán", pos: "Defensor", info: "Zaguero chileno titular." },
            { num: "6", name: "Juan Gabriel Rodríguez", pos: "Defensor", info: "Zaguero central." },
            { num: "2", name: "Rafael Pérez", pos: "Defensor", info: "Colombiano. Zaguero." },
            { num: "14", name: "Nahuel Tenaglia", pos: "Defensor", info: "Lateral derecho." },
            { num: "15", name: "Enzo Díaz", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "3", name: "Lucas Suárez", pos: "Defensor", info: "Defensor." },
            { num: "17", name: "Augusto Schott", pos: "Defensor", info: "Lateral." },
            { num: "28", name: "Juan Camilo Portillo", pos: "Mediocampista", info: "Polifuncional." },
            { num: "10", name: "Rodrigo Garro", pos: "Mediocampista", info: "Enganche. Mejor jugador." },
            { num: "30", name: "Ulises Ortegoza", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Matías Galarza", pos: "Mediocampista", info: "Volante creativo." },
            { num: "18", name: "Rodrigo Villagra", pos: "Mediocampista", info: "Volante central." },
            { num: "7", name: "Francisco Pizzini", pos: "Delantero", info: "Extremo." },
            { num: "9", name: "Michael Santos", pos: "Delantero", info: "Goleador uruguayo." },
            { num: "24", name: "Ramón Sosa", pos: "Delantero", info: "Extremo paraguayo." },
            { num: "11", name: "Valentín Depietri", pos: "Delantero", info: "Extremo juvenil." }
        ]
    },
    2023: {
        hito: "Talleres protagonista. Ramón Sosa y Rodrigo Garro figuras.",
        torneo: "Liga Profesional 2023",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Capitán." },
            { num: "1", name: "Alan Aguerre", pos: "Arquero", info: "Alternativa." },
            { num: "35", name: "Joaquín Blázquez", pos: "Arquero", info: "Tercer arquero." },
            { num: "4", name: "Matías Catalán", pos: "Defensor", info: "Selección Chile. Caudillo." },
            { num: "6", name: "Juan Gabriel Rodríguez", pos: "Defensor", info: "Zaguero central." },
            { num: "3", name: "Lucas Suárez", pos: "Defensor", info: "Defensor polivalente." },
            { num: "17", name: "Augusto Schott", pos: "Defensor", info: "Lateral derecho." },
            { num: "29", name: "Gastón Benavídez", pos: "Defensor", info: "Lateral derecho." },
            { num: "15", name: "Kevin Mantilla", pos: "Defensor", info: "Lateral izquierdo." },
            { num: "28", name: "Juan Camilo Portillo", pos: "Mediocampista", info: "El Sicario. Comodín." },
            { num: "10", name: "Rodrigo Garro", pos: "Mediocampista", info: "Enganche. 11 goles. Vendido a Corinthians." },
            { num: "30", name: "Ulises Ortegoza", pos: "Mediocampista", info: "Volante central." },
            { num: "8", name: "Matías Galarza", pos: "Mediocampista", info: "Volante creativo." },
            { num: "23", name: "Matías Esquivel", pos: "Mediocampista", info: "Enganche suplente." },
            { num: "24", name: "Ramón Sosa", pos: "Delantero", info: "Figura. Extremo veloz. Vendido a Nottingham." },
            { num: "9", name: "Michael Santos", pos: "Delantero", info: "Goleador uruguayo." },
            { num: "11", name: "Valentín Depietri", pos: "Delantero", info: "Extremo." },
            { num: "14", name: "Nahuel Bustos", pos: "Delantero", info: "Regresó a préstamo de Girona." },
            { num: "7", name: "Bruno Barticciotto", pos: "Delantero", info: "Delantero chileno." }
        ]
    },
    2024: {
        hito: "Subcampeón de Primera División. Gran nivel de Ramón Sosa y Rubén Botta.",
        torneo: "Liga Profesional / Copa Libertadores 2024",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "Capitán y máximo referente. 337 partidos en el club." },
            { num: "12", name: "Lautaro Morales", pos: "Arquero", info: "Alternativa en el arco." },
            { num: "29", name: "Gastón Benavídez", pos: "Defensor", info: "Lateral derecho indiscutido." },
            { num: "4", name: "Matías Catalán", pos: "Defensor", info: "Caudillo de la defensa. 336 partidos jugados." },
            { num: "6", name: "Juan Gabriel Rodríguez", pos: "Defensor", info: "Zaguero central sólido." },
            { num: "3", name: "Lucas Suárez", pos: "Defensor", info: "Defensor zurdo polivalente." },
            { num: "25", name: "José Luis Palomino", pos: "Defensor", info: "Refuerzo de jerarquía internacional." },
            { num: "16", name: "Miguel Navarro", pos: "Defensor", info: "Lateral izquierdo (Sel. Venezuela)." },
            { num: "17", name: "Augusto Schott", pos: "Defensor", info: "Lateral derecho de la cantera." },
            { num: "2", name: "Gabriel Báez Corradi", pos: "Defensor", info: "Lateral izquierdo sólido." },
            { num: "8", name: "Marcos Portillo", pos: "Mediocampista", info: "Volante de gran pegada." },
            { num: "27", name: "Juan Portilla", pos: "Mediocampista", info: "El colombiano, eje del medio." },
            { num: "10", name: "Rubén Botta", pos: "Mediocampista", info: "La manija del equipo. Jerarquía pura." },
            { num: "30", name: "Ulises Ortegoza", pos: "Mediocampista", info: "Dinámica y entrega." },
            { num: "24", name: "Ramón Sosa", pos: "Delantero", info: "Extremo paraguayo figura (vendido a Premier)." },
            { num: "9", name: "Federico Girotti", pos: "Delantero", info: "El Tanque goleador." },
            { num: "14", name: "Bruno Barticciotto", pos: "Delantero", info: "Atacante chileno en racha." },
            { num: "11", name: "Valentín Depietri", pos: "Delantero", info: "Velocidad por fuera." },
            { num: "7", name: "Sebastian Palacios", pos: "Delantero", info: "Regresó para aportar experiencia." },
            { num: "35", name: "Santino Barbi", pos: "Arquero", info: "Promesa del club." },
            { num: "24", name: "Juanchón Sforza", pos: "Mediocampista", info: "Volante central de jerarquía." },
            { num: "13", name: "Rodrigo Guth", pos: "Defensor", info: "Zaguero brasileño sólido." }
        ]
    },
    2025: {
        hito: "Talleres en la elite nacional. El equipo del Cacique Medina.",
        torneo: "Liga Profesional 2025",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "33 años. Titular indiscutido." },
            { num: "35", name: "Santino Barbi", pos: "Arquero", info: "20 años. Futura promesa del arco." },
            { num: "1", name: "Jeremías Florentín", pos: "Arquero", info: "19 años. Juvenil proyectado." },
            { num: "29", name: "Gastón Benavídez", pos: "Defensor", info: "Lateral derecho inamovible." },
            { num: "4", name: "Matías Catalán", pos: "Defensor", info: "33 años. Referente máximo de la defensa." },
            { num: "6", name: "Juan Gabriel Rodríguez", pos: "Defensor", info: "Zaguero central serio y firme." },
            { num: "25", name: "José Luis Palomino", pos: "Defensor", info: "36 años. Experiencia de nivel europeo." },
            { num: "2", name: "Gabriel Báez Corradi", pos: "Defensor", info: "30 años. Lateral izquierdo de jerarquía." },
            { num: "16", name: "Miguel Navarro", pos: "Defensor", info: "Lateral izquierdo de Selección." },
            { num: "17", name: "Augusto Schott", pos: "Defensor", info: "26 años. Lateral derecho." },
            { num: "3", name: "Santiago Fernández", pos: "Defensor", info: "20 años. Zaguero juvenil." },
            { num: "10", name: "Rubén Botta", pos: "Mediocampista", info: "Magia y liderazgo creativo." },
            { num: "27", name: "Juan Portilla", pos: "Mediocampista", info: "Volante central colombiano." },
            { num: "8", name: "Marcos Portillo", pos: "Mediocampista", info: "Mediocampista de buen pie." },
            { num: "5", name: "Ulises Ortegoza", pos: "Mediocampista", info: "28 años. Despliege incansable." },
            { num: "24", name: "Matías Galarza", pos: "Mediocampista", info: "23 años. Promesa paraguaya." },
            { num: "20", name: "Giovanni Baroni", pos: "Mediocampista", info: "17 años. La gran promesa de la cantera." },
            { num: "9", name: "Federico Girotti", pos: "Delantero", info: "Centrodelantero de jerarquía." },
            { num: "14", name: "Bruno Barticciotto", pos: "Delantero", info: "Goles y talento chileno." },
            { num: "7", name: "Sebastian Palacios", pos: "Delantero", info: "Atacante por las bandas." },
            { num: "11", name: "Valentín Depietri", pos: "Delantero", info: "Extremo veloz." },
            { num: "32", name: "Rodrigo Guth", pos: "Defensor", info: "25 años. Defensa brasileño." },
            { num: "15", name: "Mateo Cáceres", pos: "Mediocampista", info: "23 años. Volante con llegada." },
            { num: "21", name: "Martín Río", pos: "Mediocampista", info: "24 años. Mediocentro." },
            { num: "24", name: "Juanchón Sforza", pos: "Mediocampista", info: "Referente del medio." }
        ]
    },
    2026: {
        hito: "Regreso a la gloria continental. Guido Herrera se convierte en el jugador con más partidos en la historia profesional.",
        torneo: "CONMEBOL Libertadores / Liga Profesional 2026",
        plantel: [
            { num: "22", name: "Guido Herrera", pos: "Arquero", info: "33 años. 391 partidos y 1 gol. Leyenda viviente." },
            { num: "35", name: "Santino Barbi", pos: "Arquero", info: "20 años. Arquero de selección juvenil." },
            { num: "1", name: "Jeremías Florentín", pos: "Arquero", info: "19 años. Gran proyección internacional." },
            { num: "4", name: "Matías Catalán", pos: "Defensor", info: "33 años. 336 partidos y 14 goles." },
            { num: "2", name: "Gabriel Báez Corradi", pos: "Defensor", info: "30 años. 261 partidos y 12 goles." },
            { num: "3", name: "Santiago Fernández", pos: "Defensor", info: "20 años. 21 partidos oficiales." },
            { num: "25", name: "José Luis Palomino", pos: "Defensor", info: "36 años. Liderazgo defensivo." },
            { num: "29", name: "Gastón Benavídez", pos: "Defensor", info: "Lateral derecho inagotable." },
            { num: "16", name: "Miguel Navarro", pos: "Defensor", info: "Pilar de la selección venezolana." },
            { num: "17", name: "Augusto Schott", pos: "Defensor", info: "Lateral polifuncional." },
            { num: "5", name: "Ulises Ortegoza", pos: "Mediocampista", info: "Eje del mediocampo albiazul." },
            { num: "10", name: "Rubén Botta", pos: "Mediocampista", info: "El último diez. Calidad intacta." },
            { num: "8", name: "Marcos Portillo", pos: "Mediocampista", info: "Dueño de la pelota parada." },
            { num: "24", name: "Matías Galarza", pos: "Mediocampista", info: "Volante dinámico Selección Paraguay." },
            { num: "20", name: "Giovanni Baroni", pos: "Mediocampista", info: "Joyita de la cantera con proyección europea." },
            { num: "9", name: "Federico Girotti", pos: "Delantero", info: "Potencia goleadora en el área." },
            { num: "14", name: "Bruno Barticciotto", pos: "Delantero", info: "Extremo desequilibrante chileno." },
            { num: "7", name: "Sebastian Palacios", pos: "Delantero", info: "Experiencia y gol por las bandas." },
            { num: "11", name: "Valentín Depietri", pos: "Delantero", info: "Velocidad y gambeta." },
            { num: "19", name: "Tomás Molina", pos: "Delantero", info: "Variante ofensiva de peso." },
            { num: "32", name: "Rodrigo Guth", pos: "Defensor", info: "25 años. El brasileño, pilar del fondo." },
            { num: "24", name: "Juanchón Sforza", pos: "Mediocampista", info: "Volante central clave." }
        ]
    }
};

